# Generated by Django 4.2 on 2023-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('photo', models.ImageField(upload_to='images/home')),
                ('address', models.CharField(max_length=100, verbose_name='Manzil')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar')),
                ('num_of_rooms', models.PositiveSmallIntegerField(verbose_name='Xonalar soni')),
                ('area', models.SmallIntegerField(blank=True, verbose_name='Uy maydoni')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': '2. Home',
            },
        ),
    ]
