# Generated by Django 4.2 on 2023-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Manzil'),
        ),
    ]
