# Generated by Django 4.2 on 2023-04-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Khiva', 'Khiva'), ('Andijan', 'Andijan'), ('Namangan', 'Namangan'), ('Fergana', 'Fergana'), ('Navoi', 'Navoi'), ('Nukus', 'Nukus'), ('Urgench', 'Urgench')], default='Tashkent', max_length=100, verbose_name='Shahar'),
        ),
    ]
