# Generated by Django 4.2 on 2023-05-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home_description_alter_home_city_alter_home_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='photo',
            field=models.ImageField(upload_to='images/home'),
        ),
    ]
